version: '3.8'

volumes:
    nginx-shared-txs:
    nginx-shared-cfg:

services:
    nginx:
        image: nginx:alpine
        ports:
           - "${REVERSE_PROXY_PORT}:8000"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - nginx-shared-txs:/nginx-txs
            - nginx-shared-cfg:/nginx-cfg
        depends_on:
            - txs-web
            - cfg-web
            - cgw-web

    txs-db:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker/data/txs-db:/var/lib/postgresql/data

    cfg-db:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./docker/data/cfg-db:/var/lib/postgresql/data


    # Safe Transaction Service
    txs-redis:
        image: redis:alpine

    txs-rabbitmq:
        image: rabbitmq:alpine

    txs-web:
        image: safeglobal/safe-transaction-service:${TXS_VERSION}
        env_file:
            - ./docker/env/txs.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - ETHEREUM_NODE_URL=${RPC_NODE_URL}
        depends_on:
            - txs-db
            - txs-redis
        working_dir: /app
        volumes:
            - nginx-shared-txs:/nginx
            - ./scripts/insert_safe_master_copy.py:/app/safe_transaction_service/history/management/commands/insert_safe_master_copy.py
        command: docker/web/run_web.sh

    txs-worker-indexer: &txs-worker
        image: safeglobal/safe-transaction-service:${TXS_VERSION}
        env_file:
            - ./docker/env/txs.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - ETHEREUM_NODE_URL=${RPC_NODE_URL}
            - RUN_MIGRATIONS=1
            - WORKER_QUEUES=default,indexing
        depends_on:
            - txs-db
            - txs-redis
        command: docker/web/celery/worker/run.sh

    txs-worker-contracts-tokens:
        <<: *txs-worker
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - WORKER_QUEUES=contracts,tokens
            - ETHEREUM_NODE_URL=${RPC_NODE_URL}

    txs-worker-notifications-webhooks:
        <<: *txs-worker
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - WORKER_QUEUES=notifications,webhooks
            - ETHEREUM_NODE_URL=${RPC_NODE_URL}

    txs-scheduler:
        <<: *txs-worker
        command: docker/web/celery/scheduler/run.sh

    # Safe Config Service
    cfg-web:
        image: safeglobal/safe-config-service:${CFG_VERSION}
        tty: true
        volumes:
            - nginx-shared-cfg:/nginx
        env_file:
            - ./docker/env/cfg.env
        depends_on:
            - cfg-db

    # Safe Client Gateway
    cgw-redis:
        image: redis:alpine

    cgw-web:
        image: safeglobal/safe-client-gateway:${CGW_VERSION}
        env_file:
            - ./docker/env/cgw.env
        depends_on:
            - cgw-redis
