version: '3.8'

services:
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        env_file: .env.example
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: admin
        volumes:
            - mongo-data:/data/db
            - ./fixture/db:/docker-entrypoint-initdb.d/fixture
            - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

volumes:
    mongo-data: