version: '3.8'

# This compose file only works when used in conjunction with the default docker-compose file.
# docker compose -f docker-compose.yml -f docker-compose.api.yml

services:
    api:
        build:
            context: .
            dockerfile: apps/api/Dockerfile
            target: develop
        volumes:
            - ./coverage/apps/api:/usr/src/app/coverage/apps/api
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ./apps/api/.env.example
        environment:
            MONGODB_URI: "mongodb://root:root@mongo:27017/api?authSource=admin&ssl=false"
            MONGODB_URI_TEST_OVERRIDE: "mongodb://root:root@mongo:27017/api_test?authSource=admin&ssl=false"
            AWS_S3_PUBLIC_BUCKET_NAME: "test-thx-storage-bucket"
            AWS_S3_PRIVATE_BUCKET_NAME: "test-thx-private-storage-bucket"
            HARDHAT_RPC: "http://host.docker.internal:8545"
            HARDHAT_RPC_TEST_OVERRIDE: "http://host.docker.internal:8545"
            SAFE_TXS_SERVICE: "http://host.docker.internal:8000/txs"
            LOCAL_CERT: ""
            LOCAL_CERT_KEY: ""
            CWD: "/usr/src/app/apps/api/src/"
        ports:
            - 3001:3000
        depends_on:
            - mongo